package makanplan.dao

import scalikejdbc.*
import makanplan.model.Recipe
import makanplan.util.FoodCsvLoader

// DAO for Recipe: table ensure, basic inserts/queries, CSV import
object RecipeDao {

  // table mapping + row mapper
  object R extends SQLSyntaxSupport[Recipe] {
    override val tableName = "recipes"
    def fromRS(rs: WrappedResultSet): Recipe =
      Recipe(
        id               = rs.long("id"),
        title            = rs.string("title"),
        ingredientsText  = rs.string("ingredients"),
        instructionsText = rs.string("instructions"),
        imageName        = rs.stringOpt("image_name")
      )
  }

  // create table + index if missing
  def ensureTable()(using DBSession): Unit = {
    sql"""
      create table if not exists recipes (
        id           bigint generated by default as identity primary key,
        title        varchar(512) not null,
        ingredients  clob,
        instructions clob,
        image_name   varchar(512)
      )
    """.execute.apply()
    sql"create index if not exists idx_recipes_title on recipes(title)".execute.apply()
  }

  // wipe all rows (used for reseeding)
  def deleteAll()(using DBSession): Int =
    sql"delete from recipes".update.apply()

  // insert one and return id
  def insert(rec: Recipe)(using DBSession): Long =
    sql"""
      insert into recipes (title, ingredients, instructions, image_name)
      values (${rec.title}, ${rec.ingredientsText}, ${rec.instructionsText}, ${rec.imageName})
    """.updateAndReturnGeneratedKey.apply()

  // newest first
  def latest(limit: Int)(using DBSession): List[Recipe] =
    sql"select * from recipes order by id desc limit $limit"
      .map(R.fromRS).list.apply()

  // case-insensitive search over title/ingredients/instructions
  def search(q: String, limit: Int)(using DBSession): List[Recipe] = {
    val pat = s"%${q.toLowerCase}%"
    sql"""
      select * from recipes
      where lower(title) like $pat
         or lower(ingredients) like $pat
         or lower(instructions) like $pat
      order by title
      limit $limit
    """.map(R.fromRS).list.apply()
  }

  // list all by title
  def listAll()(using DBSession): List[Recipe] =
    sql"select * from recipes order by title"
      .map(R.fromRS).list.apply()

  // load from CSV resource; normalizes image name
  def importFromCsv(resource: String, maxRows: Int = Int.MaxValue)(using DBSession): Int = {
    val rows = FoodCsvLoader.parseRowsFromResource(resource).take(maxRows)
    rows.foreach { r =>
      val title        = r.get("Title").orElse(r.get("title")).getOrElse("").trim
      val ingredients  = r.get("Ingredients").orElse(r.get("ingredients")).getOrElse("").trim
      val instructions = r.get("Instructions").orElse(r.get("instructions")).getOrElse("").trim
      val imgRaw       = r.get("Image_Name").orElse(r.get("image_name")).getOrElse("").trim

      // default jpg; or slugified title if blank
      val fixedImg =
        if (imgRaw.nonEmpty) {
          val lower = imgRaw.toLowerCase
          if (lower.endsWith(".jpg") || lower.endsWith(".jpeg")) imgRaw else s"$imgRaw.jpg"
        } else {
          FoodCsvLoader.slugify(title) + ".jpg"
        }

      insert(
        Recipe(
          id = 0L,
          title = title,
          ingredientsText = ingredients,
          instructionsText = instructions,
          imageName = Option(fixedImg)
        )
      )
    }
    rows.length
  }

  // seed only if table is empty
  def seedFromCsvIfEmpty(resource: String, maxRows: Int)(using DBSession): Int = {
    val n = sql"select count(*) from recipes".map(_.int(1)).single.apply().getOrElse(0)
    if (n == 0) importFromCsv(resource, maxRows) else 0
  }
}
