package makanplan.util

import makanplan.dao.RecipeDao
import scalikejdbc.*

object Database:
  def init(): Unit = {
    // load H2 driver and configure a file DB (PostgreSQL mode)
    Class.forName("org.h2.Driver")
    ConnectionPool.singleton(
      "jdbc:h2:file:./makanplan_db;MODE=PostgreSQL;AUTO_SERVER=TRUE",
      "sa", ""
    )

    given DBSession = AutoSession // default session

    sql"select 1".map(_.int(1)).single.apply() // quick connectivity check

    // NOTE: call ensureSchema() here if you want app tables created at startup.
    ensureSchema()

    // recipes: make sure table exists and seed demo data
    RecipeDao.ensureTable()
    RecipeDao.seedFromCsvIfEmpty("/csv/Recipes.csv", maxRows = 30)
  }

  // create/patch core tables if missing
  private def ensureSchema()(using DBSession): Unit =
    // users
    sql"""
      create table if not exists users (
        id bigint generated by default as identity primary key,
        username varchar(255) not null unique,
        email varchar(255),
        password_hash varchar(255) not null
      )
    """.execute.apply()
    // keep email column present (safe if it already exists)
    sql"alter table users add column if not exists email varchar(255)".execute.apply()

    // settings (one row per user)
    sql"""
      create table if not exists settings (
        user_id bigint primary key,
        default_mode varchar(50) not null,
        default_budget double not null,
        constraint fk_settings_user foreign key (user_id) references users(id)
      )
    """.execute.apply()

    // dietary preferences (current schema allows one pref per user due to UNIQUE)
    sql"""
      create table if not exists dietary_preferences (
        id bigint generated by default as identity primary key,
        user_id bigint not null unique,
        preference varchar(100) not null,
        constraint fk_diet_user foreign key (user_id) references users(id)
      )
    """.execute.apply()

    // inventory items
    sql"""
      create table if not exists food_items (
        id        bigint generated by default as identity primary key,
        user_id   bigint not null,
        name      varchar(255) not null,
        category  varchar(64)  not null,
        quantity  double       not null,
        unit      varchar(32)  not null,
        expiry    date         not null,
        cost      double       not null,
        constraint fk_food_user foreign key (user_id) references users(id)
      )
    """.execute.apply()

    // weekly meal plans
    sql"""
      create table if not exists meal_plans (
        id         bigint generated by default as identity primary key,
        user_id    bigint not null,
        start_date date   not null,
        end_date   date   not null,
        constraint fk_mp_user foreign key (user_id) references users(id)
      )
    """.execute.apply()

    // meals inside a plan
    sql"""
      create table if not exists meal_plan_meals (
        id           bigint generated by default as identity primary key,
        meal_plan_id bigint not null,
        name         varchar(255) not null,
        kind         varchar(32)  not null,
        servings     int          not null,
        cost         double       not null,
        constraint fk_mpm_plan foreign key (meal_plan_id) references meal_plans(id)
      )
    """.execute.apply()

    sql"""
       create table if not exists recipe_ingredients (
         id           bigint generated by default as identity primary key,
         recipe_id    bigint not null,
         food_item_id bigint not null,
         quantity     double not null,
         unit         varchar(255) not null
       )
    """.execute.apply()